### ISSUE TITLE
최소한으로 구현해야하는 기능

### ISSUE THREAD

**Issue by kimjisu33** [iolite-ruru/catch-color#17]
### 게임 시작
- [x] 처음에 색깔 랜덤
- [x] 도망자/ 술래 설정
- [x] 랜덤 스폰 장소 -> 술래랑 도망자 위치 다르게

### 게임 종료
- [x] 시간종료 (도망자 승리)
- [x] 도망자 모두 탈락 (술래 승리)

### 게임 중
- [x] 술래 클래스
- [x] 도망자 클래스
- [x] 술래의 도망자 공격
- [x] 술래한테 같은 색의 도망자 보이지 않음 (타격은 가능)
- [x] 도망자의 색 변경 아이템
- [x] 특정 시간마다 술래의 색이 바뀜 ⇒ 아이템 획득하는 방식으로 변경
- [x] 아이템 랜덤 생성 ⇒ 아이템 생성 위치 고정

**Comment by ksy812** [comment]
현재 커서락 기능 주석처리 함.
